#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rspec-expectations
Version  : 3.3.1
Release  : 10
URL      : https://rubygems.org/downloads/rspec-expectations-3.3.1.gem
Source0  : https://rubygems.org/downloads/rspec-expectations-3.3.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-support

%description
# RSpec Expectations [![Build Status](https://secure.travis-ci.org/rspec/rspec-expectations.svg?branch=master)](http://travis-ci.org/rspec/rspec-expectations) [![Code Climate](https://codeclimate.com/github/rspec/rspec-expectations.svg)](https://codeclimate.com/github/rspec/rspec-expectations)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rspec-expectations-3.3.1
gem spec %{SOURCE0} -l --ruby > rubygem-rspec-expectations.gemspec

%build
gem build rubygem-rspec-expectations.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rspec-expectations-3.3.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rspec-expectations-3.3.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/.document
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/License.txt
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/expectation_target.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/fail_with.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/failure_aggregator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/minitest_integration.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/syntax.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/expectations/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/aliased_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/all.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/base_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/be.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/be_between.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/be_instance_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/be_kind_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/be_within.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/change.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/compound.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/contain_exactly.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/cover.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/eq.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/eql.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/equal.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/exist.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/has.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/have_attributes.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/include.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/match.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/operators.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/output.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/raise_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/respond_to.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/satisfy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/start_or_end_with.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/throw_symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/built_in/yield.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/composable.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/dsl.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/english_phrasing.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/expecteds_for_multiple_diffs.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/fail_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/generated_descriptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/matcher_delegator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rspec-expectations-3.3.1/lib/rspec/matchers/matcher_protocol.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rspec-expectations-3.3.1.gemspec
